version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongoData:/data/db
    environment:
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - "${MONGO_PORT}:27017"
    restart: on-failure
  backend:
    image: tese-backend:latest
    environment:
      MONGO_PORT: ${MONGO_PORT}
      VUE_APP_BACKEND_PORT: ${VUE_APP_BACKEND_PORT}
    links:
      - mongo
    ports:
      - "${VUE_APP_BACKEND_PORT}:10201"
    restart: on-failure
  frontend:
    image: tese-frontend:latest
    environment:
      VUE_APP_BACKEND_HOST: ${VUE_APP_BACKEND_HOST}
      VUE_APP_BACKEND_PORT: ${VUE_APP_BACKEND_PORT}
      VUE_APP_FRONTEND_PORT: ${VUE_APP_FRONTEND_PORT}
    links:
      - backend
    ports:
      - "${VUE_APP_FRONTEND_PORT}:8000"
    restart: on-failure
volumes:
  mongoData: